export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'owner' | 'admin' | 'member';
export type InvoiceStatus = 'draft' | 'sent' | 'due' | 'overdue' | 'partially_paid' | 'paid' | 'disputed';
export type PriorityLevel = 'low' | 'medium' | 'high';
export type RiskLevel = 'low' | 'medium' | 'high';
export type PreferredContact = 'email' | 'phone' | 'sms';
export type PaymentMethod = 'ACH Transfer' | 'Credit Card' | 'Bank Wire' | 'Check' | 'Other';
export type InvoiceEventType = 'created' | 'sent' | 'viewed' | 'reminder_sent' | 'payment_received' | 'status_changed' | 'note_added';
export type CommunicationChannel = 'email' | 'sms' | 'whatsapp';
export type CommunicationTone = 'gentle' | 'professional' | 'firm' | 'urgent';
export type CommunicationStatus = 'draft' | 'approved' | 'sending' | 'sent' | 'failed' | 'cancelled' | 'queued' | 'delivered';
export type RecommendationStatus = 'pending' | 'sent' | 'dismissed';
export type NotificationType = 'payment' | 'overdue' | 'copilot' | 'system';
export type SubscriptionPlan = 'Starter' | 'Professional' | 'Enterprise';
export type BillingCycle = 'monthly' | 'annual';
export type SubscriptionStatus = 'pending' | 'checkout_started' | 'trialing' | 'active' | 'past_due' | 'cancelled' | 'canceled' | 'incomplete' | 'paused' | 'expired';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          role: UserRole;
          phone: string | null;
          address: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          role?: UserRole;
          phone?: string | null;
          address?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          role?: UserRole;
          phone?: string | null;
          address?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      businesses: {
        Row: {
          id: string;
          name: string;
          industry: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          website: string | null;
          logo_url: string | null;
          service_areas: Json;
          services: Json;
          business_hours: Json;
          timezone: string;
          about: string | null;
          onboarding_completed: boolean;
          tax_id: string | null;
          currency: string;
          payment_terms_days: number;
          default_notes: string | null;
          stripe_connected: boolean;
          ach_connected: boolean;
          auto_reminder_enabled: boolean;
          omnidimension_agent_id?: string | null;
          receptionist_phone_number?: string | null;
          receptionist_provisioned_at?: string | null;
          receptionist_status?: string | null;
          receptionist_provisioning_tier?: string | null;
          receptionist_metadata?: Json | null;
          city?: string | null;
          country?: string | null;
          business_type?: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          industry?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          website?: string | null;
          logo_url?: string | null;
          service_areas?: Json;
          services?: Json;
          business_hours?: Json;
          timezone?: string;
          about?: string | null;
          onboarding_completed?: boolean;
          tax_id?: string | null;
          currency?: string;
          payment_terms_days?: number;
          default_notes?: string | null;
          stripe_connected?: boolean;
          ach_connected?: boolean;
          auto_reminder_enabled?: boolean;
          omnidimension_agent_id?: string | null;
          receptionist_phone_number?: string | null;
          receptionist_provisioned_at?: string | null;
          receptionist_status?: string | null;
          receptionist_provisioning_tier?: string | null;
          receptionist_metadata?: Json | null;
          city?: string | null;
          country?: string | null;
          business_type?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          industry?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          website?: string | null;
          logo_url?: string | null;
          service_areas?: Json;
          services?: Json;
          business_hours?: Json;
          timezone?: string;
          about?: string | null;
          onboarding_completed?: boolean;
          tax_id?: string | null;
          currency?: string;
          payment_terms_days?: number;
          default_notes?: string | null;
          stripe_connected?: boolean;
          ach_connected?: boolean;
          auto_reminder_enabled?: boolean;
          omnidimension_agent_id?: string | null;
          receptionist_phone_number?: string | null;
          receptionist_provisioned_at?: string | null;
          receptionist_status?: string | null;
          receptionist_provisioning_tier?: string | null;
          receptionist_metadata?: Json | null;
          city?: string | null;
          country?: string | null;
          business_type?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      business_members: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          role: UserRole;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          role?: UserRole;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          role?: UserRole;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          company: string;
          email: string;
          phone: string | null;
          address: string | null;
          payment_terms: number;
          risk_level: RiskLevel;
          credit_score: number;
          preferred_contact: PreferredContact;
          notes: string | null;
          sms_consent: boolean;
          sms_consent_at: string | null;
          sms_consent_source: string | null;
          sms_opted_out: boolean;
          sms_opted_out_at: string | null;
          sms_opt_out_reason: string | null;
          whatsapp_consent: boolean;
          whatsapp_consent_at: string | null;
          whatsapp_consent_source: string | null;
          whatsapp_opted_out: boolean;
          whatsapp_opted_out_at: string | null;
          whatsapp_opt_out_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          company: string;
          email: string;
          phone?: string | null;
          address?: string | null;
          payment_terms?: number;
          risk_level?: RiskLevel;
          credit_score?: number;
          preferred_contact?: PreferredContact;
          notes?: string | null;
          sms_consent?: boolean;
          sms_consent_at?: string | null;
          sms_consent_source?: string | null;
          sms_opted_out?: boolean;
          sms_opted_out_at?: string | null;
          sms_opt_out_reason?: string | null;
          whatsapp_consent?: boolean;
          whatsapp_consent_at?: string | null;
          whatsapp_consent_source?: string | null;
          whatsapp_opted_out?: boolean;
          whatsapp_opted_out_at?: string | null;
          whatsapp_opt_out_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          company?: string;
          email?: string;
          phone?: string | null;
          address?: string | null;
          payment_terms?: number;
          risk_level?: RiskLevel;
          credit_score?: number;
          preferred_contact?: PreferredContact;
          notes?: string | null;
          sms_consent?: boolean;
          sms_consent_at?: string | null;
          sms_consent_source?: string | null;
          sms_opted_out?: boolean;
          sms_opted_out_at?: string | null;
          sms_opt_out_reason?: string | null;
          whatsapp_consent?: boolean;
          whatsapp_consent_at?: string | null;
          whatsapp_consent_source?: string | null;
          whatsapp_opted_out?: boolean;
          whatsapp_opted_out_at?: string | null;
          whatsapp_opt_out_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string;
          invoice_number: string;
          issue_date: string;
          due_date: string;
          currency: string;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          discount_amount: number;
          original_amount: number;
          amount_paid: number;
          payments_received?: number;
          remaining_balance: number;
          status: InvoiceStatus;
          priority: PriorityLevel;
          paid_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id: string;
          invoice_number: string;
          issue_date?: string;
          due_date: string;
          currency?: string;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          original_amount: number;
          amount_paid?: number;
          payments_received?: number;
          remaining_balance: number;
          status?: InvoiceStatus;
          priority?: PriorityLevel;
          paid_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string;
          invoice_number?: string;
          issue_date?: string;
          due_date?: string;
          currency?: string;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          original_amount?: number;
          amount_paid?: number;
          payments_received?: number;
          remaining_balance?: number;
          status?: InvoiceStatus;
          priority?: PriorityLevel;
          paid_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          tax_amount: number;
          discount_amount: number;
          line_total: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity?: number;
          unit_price?: number;
          tax_amount?: number;
          discount_amount?: number;
          line_total?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          tax_amount?: number;
          discount_amount?: number;
          line_total?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          business_id: string;
          invoice_id: string;
          customer_id?: string | null;
          amount: number;
          currency?: string;
          payment_date: string;
          method: PaymentMethod;
          status?: string;
          provider?: string;
          provider_transaction_id?: string | null;
          completed_at?: string | null;
          failure_reason?: string | null;
          refunded_amount?: number;
          secure_token?: string | null;
          reference: string | null;
          notes: string | null;
          metadata?: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          invoice_id: string;
          customer_id?: string | null;
          amount: number;
          currency?: string;
          payment_date?: string;
          method: PaymentMethod;
          status?: string;
          provider?: string;
          provider_transaction_id?: string | null;
          completed_at?: string | null;
          failure_reason?: string | null;
          refunded_amount?: number;
          secure_token?: string | null;
          reference?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          invoice_id?: string;
          customer_id?: string | null;
          amount?: number;
          currency?: string;
          payment_date?: string;
          method?: PaymentMethod;
          status?: string;
          provider?: string;
          provider_transaction_id?: string | null;
          completed_at?: string | null;
          failure_reason?: string | null;
          refunded_amount?: number;
          secure_token?: string | null;
          reference?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      invoice_events: {
        Row: {
          id: string;
          invoice_id: string;
          business_id: string;
          event_type: InvoiceEventType;
          title: string;
          description: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          business_id: string;
          event_type: InvoiceEventType;
          title: string;
          description?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          business_id?: string;
          event_type?: InvoiceEventType;
          title?: string;
          description?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      communications: {
        Row: {
          id: string;
          business_id: string;
          invoice_id: string | null;
          customer_id: string | null;
          lead_id: string | null;
          appointment_id: string | null;
          job_id: string | null;
          template_id: string | null;
          channel: CommunicationChannel;
          subject: string | null;
          message: string;
          tone: CommunicationTone;
          status: CommunicationStatus;
          trigger_type: string | null;
          approval_status: 'auto_approved' | 'pending_approval' | 'approved' | 'rejected';
          approved_by: string | null;
          approved_at: string | null;
          rejection_reason: string | null;
          idempotency_key: string | null;
          requires_approval: boolean;
          sent_at: string | null;
          provider_message_id: string | null;
          error_message: string | null;
          delivery_status: string | null;
          template_name: string | null;
          template_language: string | null;
          template_variables: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          invoice_id?: string | null;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          job_id?: string | null;
          template_id?: string | null;
          channel: CommunicationChannel;
          subject?: string | null;
          message: string;
          tone?: CommunicationTone;
          status?: CommunicationStatus;
          trigger_type?: string | null;
          approval_status?: 'auto_approved' | 'pending_approval' | 'approved' | 'rejected';
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          idempotency_key?: string | null;
          requires_approval?: boolean;
          sent_at?: string | null;
          provider_message_id?: string | null;
          error_message?: string | null;
          delivery_status?: string | null;
          template_name?: string | null;
          template_language?: string | null;
          template_variables?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          invoice_id?: string | null;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          job_id?: string | null;
          template_id?: string | null;
          channel?: CommunicationChannel;
          subject?: string | null;
          message?: string;
          tone?: CommunicationTone;
          status?: CommunicationStatus;
          trigger_type?: string | null;
          approval_status?: 'auto_approved' | 'pending_approval' | 'approved' | 'rejected';
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          idempotency_key?: string | null;
          requires_approval?: boolean;
          sent_at?: string | null;
          provider_message_id?: string | null;
          error_message?: string | null;
          delivery_status?: string | null;
          template_name?: string | null;
          template_language?: string | null;
          template_variables?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ai_recommendations: {
        Row: {
          id: string;
          business_id: string;
          invoice_id: string;
          customer_name: string | null;
          amount: number;
          days_overdue: number;
          priority: PriorityLevel;
          recommended_action: string;
          reason: string;
          tone: CommunicationTone;
          message_draft_subject: string | null;
          message_draft: string;
          confidence: number;
          status: RecommendationStatus;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          invoice_id: string;
          customer_name?: string | null;
          amount?: number;
          days_overdue?: number;
          priority?: PriorityLevel;
          recommended_action: string;
          reason: string;
          tone?: CommunicationTone;
          message_draft_subject?: string | null;
          message_draft: string;
          confidence?: number;
          status?: RecommendationStatus;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          invoice_id?: string;
          customer_name?: string | null;
          amount?: number;
          days_overdue?: number;
          priority?: PriorityLevel;
          recommended_action?: string;
          reason?: string;
          tone?: CommunicationTone;
          message_draft_subject?: string | null;
          message_draft?: string;
          confidence?: number;
          status?: RecommendationStatus;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          type: NotificationType;
          title: string;
          message: string;
          link_url: string | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          type: NotificationType;
          title: string;
          message: string;
          link_url?: string | null;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string | null;
          type?: NotificationType;
          title?: string;
          message?: string;
          link_url?: string | null;
          read?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id?: string | null;
          business_id: string;
          plan: SubscriptionPlan;
          billing_cycle: BillingCycle;
          status: SubscriptionStatus;
          selected_plan?: string | null;
          selected_billing_cycle?: string | null;
          checkout_session_id?: string | null;
          price_amount: number;
          currency: string;
          provider: string | null;
          provider_customer_id: string | null;
          provider_subscription_id: string | null;
          trial_start: string | null;
          trial_end: string | null;
          trial_ends_at: string | null;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          business_id: string;
          plan?: SubscriptionPlan;
          billing_cycle?: BillingCycle;
          status?: SubscriptionStatus;
          selected_plan?: string | null;
          selected_billing_cycle?: string | null;
          checkout_session_id?: string | null;
          price_amount?: number;
          currency?: string;
          provider?: string | null;
          provider_customer_id?: string | null;
          provider_subscription_id?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          trial_ends_at?: string | null;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          business_id?: string;
          plan?: SubscriptionPlan;
          billing_cycle?: BillingCycle;
          status?: SubscriptionStatus;
          selected_plan?: string | null;
          selected_billing_cycle?: string | null;
          checkout_session_id?: string | null;
          price_amount?: number;
          currency?: string;
          provider?: string | null;
          provider_customer_id?: string | null;
          provider_subscription_id?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          trial_ends_at?: string | null;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      processed_webhook_events: {
        Row: {
          id: string;
          provider: string;
          event_type: string;
          payload: Json;
          processed_at: string;
        };
        Insert: {
          id: string;
          provider: string;
          event_type: string;
          payload?: Json;
          processed_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          event_type?: string;
          payload?: Json;
          processed_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          business_id: string | null;
          user_id: string | null;
          action: string;
          entity: string;
          entity_id: string | null;
          metadata: Json;
          timestamp: string;
        };
        Insert: {
          id?: string;
          business_id?: string | null;
          user_id?: string | null;
          action: string;
          entity: string;
          entity_id?: string | null;
          metadata?: Json;
          timestamp?: string;
        };
        Update: {
          id?: string;
          business_id?: string | null;
          user_id?: string | null;
          action?: string;
          entity?: string;
          entity_id?: string | null;
          metadata?: Json;
          timestamp?: string;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          key: string;
          count: number;
          window_start: string;
          expires_at: string;
        };
        Insert: {
          key: string;
          count?: number;
          window_start?: string;
          expires_at: string;
        };
        Update: {
          key?: string;
          count?: number;
          window_start?: string;
          expires_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          name: string;
          company: string | null;
          phone: string | null;
          email: string | null;
          source: string;
          service_requested: string | null;
          status: string;
          priority: string;
          estimated_value: number;
          score: number;
          assigned_user_id: string | null;
          assigned_user_name: string | null;
          notes: string | null;
          last_activity_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          name: string;
          company?: string | null;
          phone?: string | null;
          email?: string | null;
          source?: string;
          service_requested?: string | null;
          status?: string;
          priority?: string;
          estimated_value?: number;
          score?: number;
          assigned_user_id?: string | null;
          assigned_user_name?: string | null;
          notes?: string | null;
          last_activity_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          name?: string;
          company?: string | null;
          phone?: string | null;
          email?: string | null;
          source?: string;
          service_requested?: string | null;
          status?: string;
          priority?: string;
          estimated_value?: number;
          score?: number;
          assigned_user_id?: string | null;
          assigned_user_name?: string | null;
          notes?: string | null;
          last_activity_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_notes: {
        Row: {
          id: string;
          business_id: string;
          lead_id: string;
          author_id: string | null;
          author_name: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          lead_id: string;
          author_id?: string | null;
          author_name: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          lead_id?: string;
          author_id?: string | null;
          author_name?: string;
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_activities: {
        Row: {
          id: string;
          business_id: string;
          lead_id: string;
          user_id: string | null;
          activity_type: string;
          title: string;
          description: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          lead_id: string;
          user_id?: string | null;
          activity_type: string;
          title: string;
          description?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          lead_id?: string;
          user_id?: string | null;
          activity_type?: string;
          title?: string;
          description?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          lead_id: string | null;
          title: string;
          service_type: string;
          start_time: string;
          end_time: string;
          status: string;
          address: string | null;
          technician_name: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          lead_id?: string | null;
          title: string;
          service_type: string;
          start_time: string;
          end_time: string;
          status?: string;
          address?: string | null;
          technician_name?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          lead_id?: string | null;
          title?: string;
          service_type?: string;
          start_time?: string;
          end_time?: string;
          status?: string;
          address?: string | null;
          technician_name?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          lead_id: string | null;
          appointment_id: string | null;
          invoice_id: string | null;
          estimate_id: string | null;
          title: string;
          service_type: string;
          description: string | null;
          property_address: string | null;
          status: string;
          priority: string;
          scheduled_date: string | null;
          estimated_duration_minutes: number;
          start_time: string | null;
          end_time: string | null;
          estimated_total: number;
          actual_total: number;
          assigned_tech_id: string | null;
          assigned_tech_name: string | null;
          technician_name: string | null;
          notes: string | null;
          internal_notes: string | null;
          customer_notes: string | null;
          completed_at: string | null;
          completed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          invoice_id?: string | null;
          estimate_id?: string | null;
          title: string;
          service_type: string;
          description?: string | null;
          property_address?: string | null;
          status?: string;
          priority?: string;
          scheduled_date?: string | null;
          estimated_duration_minutes?: number;
          start_time?: string | null;
          end_time?: string | null;
          estimated_total?: number;
          actual_total?: number;
          assigned_tech_id?: string | null;
          assigned_tech_name?: string | null;
          technician_name?: string | null;
          notes?: string | null;
          internal_notes?: string | null;
          customer_notes?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          invoice_id?: string | null;
          estimate_id?: string | null;
          title?: string;
          service_type?: string;
          description?: string | null;
          property_address?: string | null;
          status?: string;
          priority?: string;
          scheduled_date?: string | null;
          estimated_duration_minutes?: number;
          start_time?: string | null;
          end_time?: string | null;
          estimated_total?: number;
          actual_total?: number;
          assigned_tech_id?: string | null;
          assigned_tech_name?: string | null;
          technician_name?: string | null;
          notes?: string | null;
          internal_notes?: string | null;
          customer_notes?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      estimates: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          job_id: string | null;
          lead_id: string | null;
          estimate_number: string;
          title: string;
          description: string | null;
          items: Json;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          discount_amount: number;
          total_amount: number;
          status: string;
          valid_until: string | null;
          notes: string | null;
          created_by: string | null;
          approved_at: string | null;
          approved_by_customer_name: string | null;
          rejected_at: string | null;
          rejection_reason: string | null;
          invoice_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          job_id?: string | null;
          lead_id?: string | null;
          estimate_number: string;
          title: string;
          description?: string | null;
          items?: Json;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          status?: string;
          valid_until?: string | null;
          notes?: string | null;
          created_by?: string | null;
          approved_at?: string | null;
          approved_by_customer_name?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          job_id?: string | null;
          lead_id?: string | null;
          estimate_number?: string;
          title?: string;
          description?: string | null;
          items?: Json;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          status?: string;
          valid_until?: string | null;
          notes?: string | null;
          created_by?: string | null;
          approved_at?: string | null;
          approved_by_customer_name?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      job_activities: {
        Row: {
          id: string;
          business_id: string;
          job_id: string;
          activity_type: string;
          title: string;
          description: string | null;
          metadata: Json;
          user_id: string | null;
          user_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          job_id: string;
          activity_type: string;
          title: string;
          description?: string | null;
          metadata?: Json;
          user_id?: string | null;
          user_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          job_id?: string;
          activity_type?: string;
          title?: string;
          description?: string | null;
          metadata?: Json;
          user_id?: string | null;
          user_name?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      receptionist_settings: {
        Row: {
          id: string;
          business_id: string;
          enabled: boolean;
          greeting: string;
          business_description: string;
          tone: string;
          languages: Json;
          after_hours_message: string;
          emergency_instructions: string;
          booking_enabled: boolean;
          booking_lead_time_hours: number;
          booking_max_days_ahead: number;
          human_handoff_keywords: Json;
          faqs: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          enabled?: boolean;
          greeting?: string;
          business_description?: string;
          tone?: string;
          languages?: Json;
          after_hours_message?: string;
          emergency_instructions?: string;
          booking_enabled?: boolean;
          booking_lead_time_hours?: number;
          booking_max_days_ahead?: number;
          human_handoff_keywords?: Json;
          faqs?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          enabled?: boolean;
          greeting?: string;
          business_description?: string;
          tone?: string;
          languages?: Json;
          after_hours_message?: string;
          emergency_instructions?: string;
          booking_enabled?: boolean;
          booking_lead_time_hours?: number;
          booking_max_days_ahead?: number;
          human_handoff_keywords?: Json;
          faqs?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      receptionist_services: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          category: string;
          description: string;
          typical_duration_minutes: number;
          emergency_available: boolean;
          booking_eligible: boolean;
          base_price: number;
          qualification_questions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          category?: string;
          description?: string;
          typical_duration_minutes?: number;
          emergency_available?: boolean;
          booking_eligible?: boolean;
          base_price?: number;
          qualification_questions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          category?: string;
          description?: string;
          typical_duration_minutes?: number;
          emergency_available?: boolean;
          booking_eligible?: boolean;
          base_price?: number;
          qualification_questions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      receptionist_conversations: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          lead_id: string | null;
          appointment_id: string | null;
          channel: string;
          state: string;
          detected_intent: string | null;
          intent_confidence: number | null;
          customer_name: string | null;
          customer_phone: string | null;
          customer_email: string | null;
          customer_address: string | null;
          service_requested: string | null;
          urgency: string;
          handoff_required: boolean;
          handoff_reason: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          channel?: string;
          state?: string;
          detected_intent?: string | null;
          intent_confidence?: number | null;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          customer_address?: string | null;
          service_requested?: string | null;
          urgency?: string;
          handoff_required?: boolean;
          handoff_reason?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          lead_id?: string | null;
          appointment_id?: string | null;
          channel?: string;
          state?: string;
          detected_intent?: string | null;
          intent_confidence?: number | null;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          customer_address?: string | null;
          service_requested?: string | null;
          urgency?: string;
          handoff_required?: boolean;
          handoff_reason?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      receptionist_messages: {
        Row: {
          id: string;
          business_id: string;
          conversation_id: string;
          sender_type: string;
          content: string;
          structured_payload: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          conversation_id: string;
          sender_type: string;
          content: string;
          structured_payload?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          conversation_id?: string;
          sender_type?: string;
          content?: string;
          structured_payload?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      communication_templates: {
        Row: {
          id: string;
          business_id: string | null;
          name: string;
          channel: CommunicationChannel;
          category: string;
          subject_template: string | null;
          body_template: string;
          variables: Json;
          is_system: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id?: string | null;
          name: string;
          channel: CommunicationChannel;
          category: string;
          subject_template?: string | null;
          body_template: string;
          variables?: Json;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string | null;
          name?: string;
          channel?: CommunicationChannel;
          category?: string;
          subject_template?: string | null;
          body_template?: string;
          variables?: Json;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      communication_consents: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          lead_id: string | null;
          channel: CommunicationChannel;
          opted_in: boolean;
          consent_source: string | null;
          consent_at: string | null;
          opted_out: boolean;
          opted_out_at: string | null;
          opt_out_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          lead_id?: string | null;
          channel: CommunicationChannel;
          opted_in?: boolean;
          consent_source?: string | null;
          consent_at?: string | null;
          opted_out?: boolean;
          opted_out_at?: string | null;
          opt_out_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          lead_id?: string | null;
          channel?: CommunicationChannel;
          opted_in?: boolean;
          consent_source?: string | null;
          consent_at?: string | null;
          opted_out?: boolean;
          opted_out_at?: string | null;
          opt_out_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      review_settings: {
        Row: {
          id: string;
          business_id: string;
          automation_enabled: boolean;
          request_delay_hours: number;
          primary_platform: string;
          google_review_url: string | null;
          direct_feedback_url: string | null;
          default_channel: 'email' | 'sms' | 'whatsapp';
          max_requests_per_job: number;
          positive_threshold: number;
          email_subject_template: string | null;
          email_body_template: string | null;
          sms_body_template: string | null;
          whatsapp_body_template: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          automation_enabled?: boolean;
          request_delay_hours?: number;
          primary_platform?: string;
          google_review_url?: string | null;
          direct_feedback_url?: string | null;
          default_channel?: 'email' | 'sms' | 'whatsapp';
          max_requests_per_job?: number;
          positive_threshold?: number;
          email_subject_template?: string | null;
          email_body_template?: string | null;
          sms_body_template?: string | null;
          whatsapp_body_template?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          automation_enabled?: boolean;
          request_delay_hours?: number;
          primary_platform?: string;
          google_review_url?: string | null;
          direct_feedback_url?: string | null;
          default_channel?: 'email' | 'sms' | 'whatsapp';
          max_requests_per_job?: number;
          positive_threshold?: number;
          email_subject_template?: string | null;
          email_body_template?: string | null;
          sms_body_template?: string | null;
          whatsapp_body_template?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      review_requests: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string | null;
          customer_name: string;
          customer_phone: string | null;
          customer_email: string | null;
          job_id: string | null;
          technician_id: string | null;
          technician_name: string | null;
          channel: string;
          status: string;
          scheduled_for: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          opened_at: string | null;
          completed_at: string | null;
          review_url: string | null;
          feedback_url: string | null;
          idempotency_key: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id?: string | null;
          customer_name: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          job_id?: string | null;
          technician_id?: string | null;
          technician_name?: string | null;
          channel?: string;
          status?: string;
          scheduled_for?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          completed_at?: string | null;
          review_url?: string | null;
          feedback_url?: string | null;
          idempotency_key?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string | null;
          customer_name?: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          job_id?: string | null;
          technician_id?: string | null;
          technician_name?: string | null;
          channel?: string;
          status?: string;
          scheduled_for?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          completed_at?: string | null;
          review_url?: string | null;
          feedback_url?: string | null;
          idempotency_key?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customer_feedback: {
        Row: {
          id: string;
          business_id: string;
          review_request_id: string | null;
          customer_id: string | null;
          customer_name: string;
          customer_phone: string | null;
          customer_email: string | null;
          job_id: string | null;
          technician_name: string | null;
          rating: number;
          sentiment: string;
          feedback_text: string | null;
          service_aspects: Json;
          channel: string;
          follow_up_status: string;
          follow_up_notes: string | null;
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          review_request_id?: string | null;
          customer_id?: string | null;
          customer_name: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          job_id?: string | null;
          technician_name?: string | null;
          rating: number;
          sentiment: string;
          feedback_text?: string | null;
          service_aspects?: Json;
          channel?: string;
          follow_up_status?: string;
          follow_up_notes?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          review_request_id?: string | null;
          customer_id?: string | null;
          customer_name?: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          job_id?: string | null;
          technician_name?: string | null;
          rating?: number;
          sentiment?: string;
          feedback_text?: string | null;
          service_aspects?: Json;
          channel?: string;
          follow_up_status?: string;
          follow_up_notes?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      review_events: {
        Row: {
          id: string;
          business_id: string;
          review_request_id: string;
          event_type: string;
          payload: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          review_request_id: string;
          event_type: string;
          payload?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          review_request_id?: string;
          event_type?: string;
          payload?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      review_templates: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          channel: string;
          subject_template: string | null;
          body_template: string;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          channel: string;
          subject_template?: string | null;
          body_template: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          channel?: string;
          subject_template?: string | null;
          body_template?: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      usage_records: {
        Row: {
          id: string;
          business_id: string;
          metric: string;
          period_start: string;
          period_end: string;
          usage_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          metric: string;
          period_start?: string;
          period_end?: string;
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          metric?: string;
          period_start?: string;
          period_end?: string;
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_events: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          event_type: string;
          from_plan: string | null;
          to_plan: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          event_type: string;
          from_plan?: string | null;
          to_plan?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string | null;
          event_type?: string;
          from_plan?: string | null;
          to_plan?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      payment_requests: {
        Row: {
          id: string;
          business_id: string;
          invoice_id: string;
          customer_id: string | null;
          secure_token: string;
          channel: string;
          status: string;
          amount_requested: number;
          expires_at: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          invoice_id: string;
          customer_id?: string | null;
          secure_token: string;
          channel: string;
          status?: string;
          amount_requested: number;
          expires_at: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          invoice_id?: string;
          customer_id?: string | null;
          secure_token?: string;
          channel?: string;
          status?: string;
          amount_requested?: number;
          expires_at?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      refunds: {
        Row: {
          id: string;
          business_id: string;
          payment_id: string;
          invoice_id: string;
          amount: number;
          reason: string;
          status: string;
          provider_refund_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          payment_id: string;
          invoice_id: string;
          amount: number;
          reason: string;
          status?: string;
          provider_refund_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          payment_id?: string;
          invoice_id?: string;
          amount?: number;
          reason?: string;
          status?: string;
          provider_refund_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
