import { MetadataRoute } from 'next';
import { BRAND } from '@/config/brand';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/pricing',
          '/features',
          '/about',
          '/security',
          '/contact',
          '/privacy',
          '/terms',
          '/subscription-terms',
          '/refund-policy',
          '/dpa',
          '/sla',
          '/acceptable-use',
          '/ip-policy',
          '/data-retention',
          '/account-deletion',
          '/demo',
        ],
        disallow: [
          '/login',
          '/signup',
          '/forgot-password',
          '/reset-password',
          '/auth',
          '/auth/',
          '/billing',
          '/billing/',
          '/onboarding',
          '/onboarding/',
          '/dashboard',
          '/dashboard/',
          '/settings',
          '/settings/',
          '/admin',
          '/admin/',
          '/agency',
          '/agency/',
          '/api',
          '/api/',
          '/leads',
          '/pipeline',
          '/jobs',
          '/invoices',
          '/estimates',
          '/customers',
          '/appointments',
          '/contacts',
          '/copilot',
          '/receptionist',
          '/communications',
          '/reputation',
          '/payments',
          '/collections',
          '/follow-up',
          '/reports',
          '/notifications',
          '/profile',
          '/pay/',
        ],
      },
    ],
    sitemap: `${BRAND.domain}/sitemap.xml`,
  };
}
